config/routes.rb
Rails.application.routes.draw do
  resources :quotes do
    member do
      post 'vote'
      get 'vote'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
 # root "pages#home"
    root "quotes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
  after_initialize :init

  validates :year, numericality: { only_integer: true, allow_blank: true, greater_than_or_equal_to: 1800, less_than_or_equal_to: Date.current.year }
   validates :saying, presence: true
  validates :said_by, presence: true

  def init
    self.votes_count ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy vote]

  # GET /quotes
  def index
     sort_by = params[:sort_by]

    if sort_by == 'year'
      @quotes = Quote.order(year: :asc)
    elsif sort_by == 'said_by'
      @quotes = Quote.order(said_by: :asc)
    elsif sort_by == 'saying'
      @quotes = Quote.order(saying: :asc)
    else
      @quotes = Quote.all
    end
  end

  # GET /quotes/1
  def show
    @quote
  end

  def vote
    # Adjust the logic based on your voting requirements
    if params[:type] == 'upvote'
      @quote.increment!(:votes_count)
    elsif params[:type] == 'downvote'
      @quote.decrement!(:votes_count)
    end
    redirect_to quotes_path
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path, notice: "Quote was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /quotes/1
  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /quotes/1
  def destroy
    @quote.destroy!
    redirect_to quotes_url, notice: "Quote was successfully deleted.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:saying, :said_by, :year, :notes)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ror</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container pt-5">
  <h1><i class="bi bi-gem" style="color: red;"></i> Coming soon</h1>
  <p>Site is under construction</p>
</div>

app/views/quotes/_form.html.erb
<div class="container">
  <%= form_with(model: quote) do |form| %>
    <% if quote.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

        <ul>
          <% quote.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :saying, class: "form-label" %>
      <%= form.text_field :saying, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :said_by, class: "form-label" %>
      <%= form.text_field :said_by, class: "form-control" %>
    </div>

    <div class="mb-3">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :notes %>
    <%= form.rich_text_area :notes, class: "form-control" %>
  </div>

    <div class="mt-3">
      <%= form.submit "Update Quote", class: "btn btn-primary" %>
      <%= link_to "Cancel", quotes_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

  <!-- Footer -->
<footer class="container">
  <p class="bg-dark text-white text-center footer mt-5"> &copy All rights reserved - WEB 3200 - 2024</p>
  </footer>

app/views/quotes/_quote.html.erb
<div class="card w-100 d-flex">
  <div class="card-header">
    <div class="d-flex justify-content-between fs-5">
      <strong class="d-flex">Quote  <% if quote.year.present? %>
        <p class="card-text ms-2">  (<%= quote.year %>)</p>
      <% end %></strong>
      <p class="card-text flex-end fs-5"><strong><%= quote.votes_count %></strong></p>
    </div>
  </div>
  <div class="card-body w-100">
    <h5 class="card-title"><%= quote.saying %></h5>
    <p class="card-text"><i class="bi bi-dash-lg"></i> <%= quote.said_by %></p>
    <% if quote.notes.present? %>
      <p class="fw-bold">NOTES:</p>
      <p> <%= raw quote.notes %></p>
    <% end %>
    <div class="d-flex gap-2">
      <%= link_to "Edit", edit_quote_path(quote), class: 'btn btn-primary bi-trash3' %>
      <%= link_to 'vote', vote_quote_path(quote, type: 'upvote'), method: :post, class: 'btn btn-success bi-hand-thumbs-up ' %>
      <%= button_to "Delete", quote, method: :delete, class: 'btn btn-danger bi-trash3', data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/quotes/edit.html.erb
<h1 class="bi bi-chat-square-quote-fill text-primary text-center display-1"></h1>
<div class="container">
<h1 class="text-primary">Editing quote</h1>
<hr>
<%= render "form", quote: @quote %>
</div>

app/views/quotes/index.html.erb
<div class="container">
  <h1 class="bi bi-chat-square-quote-fill text-primary text-center display-1"></h1>
      <p style="color: green"><%= notice %></p>

      <div class="d-flex justify-content-between">
      <h1 class="text-primary">Quotes</h1>
  <div class=" d-flex align-items-center">
      <%= link_to url_for(sort_by: 'year') do %>
      <button class="btn border-1 border-primary text-primary me-2 fw-semibold btn-sort"> <i class="bi bi-sort-numeric-down"></i>Sort by Year</button>
    <% end %>

    <%= link_to url_for(sort_by: 'said_by') do %>
      <button class="btn border-1 border-primary text-primary me-2 fw-semibold btn-sort"> <i class="bi bi-sort-down-alt"></i>Sort by Said By</button>
    <% end %>

    <%= link_to url_for(sort_by: 'saying') do %>
      <button class="btn border-1 border-primary text-primary me-2 fw-semibold btn-sort"> <i class="bi bi-sort-down-alt"></i> Sort by Saying</button>
    <% end %>

      <%= link_to new_quote_path, class: "btn btn-primary h-75" do %>
      <i class="bi bi-plus"></i> New Quote
      <% end %>
      </div>
</div>
      <hr>
       <% if @quotes.any? %>
    <div class="row">
      <% @quotes.each do |quote| %>
        <div class="mb-3">
          <%= render partial: 'quote', locals: { quote: quote } %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>Nothing to show.</p>
  <% end %>
</div>

<footer class="container">
  <p class="bg-dark text-white text-center footer"> &copy All rights reserved - WEB 3200 - 2024</p>
  </footer>

app/views/quotes/new.html.erb
  <h1 class="bi bi-chat-square-quote-fill text-primary text-center display-1"></h1>
<div class="container d-flex flex-column mt-5">

<h1 class="text-primary">Add a new quote</h1>

<hr>

  <%= render "form", quote: @quote %>
</div>
  

app/views/quotes/show.html.erb
<div class="container">
<h1 class="bi bi-chat-square-quote-fill text-primary text-center display-1"></h1>
<p style="color: green"><%= notice %></p>

<%= render "quote", quote: @quote %>

</div>